image: maven:latest

stages:
  - lint
  - build
  - test
  - publish

checkstyle:
  stage: lint
  needs: []
  script:
    - mvn checkstyle:checkstyle

compile:
  stage: build
  needs: []
  script:
    - mvn install

junit:
  stage: test
  needs: [compile]
  script:
    - mvn test
  artifacts:
    reports:
      junit: target/surefire-reports/*.xml

pages:
  stage: publish
  needs: [junit]
  script:
    - mkdir public
    - mvn javadoc:jar
    - cp target/apidocs/* public/
  artifacts:
    paths:
      - public
  only: [master]
