image: maven:latest

stages:
  - lint
  - build
  - test
  - publish

checkstyle:
  stage: lint
  needs: []
  script:
    - mvn checkstyle:checkstyle

compile:
  stage: build
  needs: []
  script:
    - mvn install

docs:
  stage: build
  needs: []
  script:
    - mvn javadoc:jar

junit:
  stage: test
  needs: [compile]
  script:
    - mvn test
  artifacts:
    reports:
      junit: target/surefire-reports/*.xml

pages:
  stage: publish
  needs: [junit]
  script: sh scripts/pages.sh
  after_script:
    - mv .public public
  artifacts:
    paths:
      - public
  only: [master]
